version: '3'

services:
  academic-search-mcp-server:
    image: python:3.11-slim
    container_name: academic-search-mcp-server
    working_dir: /app
    volumes:
      - ../data/academic-search:/app/data
    ports:
      - "8002:8002"
    environment:
      - ACADEMIC_SEARCH_STORAGE_PATH=/app/data
      - SEMANTIC_SCHOLAR_API_KEY=${SEMANTIC_SCHOLAR_API_KEY:-}
      - PUBMED_API_KEY=${PUBMED_API_KEY:-}
    command: >
      bash -c "pip install academic-search-mcp-server && 
               academic-search-mcp-server --port 8002 --storage-path /app/data"
    networks:
      - reagent-network

networks:
  reagent-network:
    driver: bridge
