# LLM Configuration
llm:
  thinking_provider: "openrouter_quasar"
  strategy_writer_provider: "openrouter_quasar"
  research_provider: "openrouter_llama4-scout"
  openrouter_quasar:
    model: "openrouter/optimus-alpha"
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.7
    max_tokens: 5000
    timeout: 60
    context_window_in_k: 1000  # ~128K tokens context window for quasar
  openrouter_deepseek:
    model: "openrouter/deepseek-coder-33b-instruct"
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.7
    max_tokens: 5000
    timeout: 60
    context_window_in_k: 128  # ~100K tokens context window
  openrouter_llama4-scout:
    model: "meta-llama/llama-4-scout:free"
    base_url: "https://openrouter.ai/api/v1"
    temperature: 0.7
    max_tokens: 5000
    timeout: 60
    context_window_in_k: 10000  # ~196K tokens context window
  ollama_qwen:
    model: "qwen:latest"
    base_url: "http://localhost:11434"
    timeout: 60
    context_window_in_k: 32  # ~32K tokens context window for qwen
  ollama_deepseek:
    model: "deepseek-coder:33b"
    base_url: "http://localhost:11434"
    timeout: 60
    context_window_in_k: 128  # ~32K tokens context window

# Agent Configuration
agents:
  researcher:
    name: "IdeaResearcherAgent"
    tools: ["web_search", "pdf_reader", "file_manager"]
    max_iterations: 5
    research_folder: "research_ideas"
    
  backtest_analyzer:
    name: "BacktestAnalyzerAgent"
    tools: ["data_analyzer", "metric_calculator"]
    max_iterations: 3
    
  strategy_developer:
    name: "StrategyDeveloperAgent"
    tools: ["code_writer", "code_analyzer"]
    max_iterations: 5
    
  backtester:
    name: "BacktesterAgent"
    tools: ["lean_cli"]
    max_iterations: 2
    test_data:
      min_period: "1Y"  # 1 year minimum for testing
      train_split: 0.7  # 70% for training
    
  reporter:
    name: "ReportingAgent"
    tools: ["logger", "notification"]
    update_interval: 300  # seconds

# Tool Configuration
tools:
  web_search:
    engines: ["google", "arxiv"]
    max_results: 10
    
  pdf_reader:
    supported_formats: ["pdf", "html"]
    max_file_size: 10485760  # 10MB
    
  lean_cli:
    backtest_command: "lean backtest"
    timeout: 3600  # 1 hour
    
  logger:
    level: "INFO"
    file: "system.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# System Configuration
system:
  base_path: "/Users/vandanchopra/Vandan_Personal_Folder/CODE_STUFF/Projects/MathematricksQ/AgenticDeveloper"
  strategies_path: "../Strategies"
  human_pause_duration: 15  # seconds
  max_concurrent_agents: 3
  debug_mode: false