urls:
- category: academic
  description: Recent quantitative finance papers
  url: https://arxiv.org/list/q-fin/recent
- category: academic
  description: SSRN Trading and Market Microstructure
  url: https://papers.ssrn.com/sol3/papers.cfm?topic=2806
